const VLQ_BASE_SHIFT = 5;

const VLQ_BASE = 1 << VLQ_BASE_SHIFT; // 左移5位：32

const VLQ_BASE_MASK = VLQ_BASE - 1; // 31

const VLQ_CONTINUATION_BIT = VLQ_BASE;

export { VLQ_BASE_SHIFT, VLQ_BASE, VLQ_BASE_MASK, VLQ_CONTINUATION_BIT };
